### ISSUE TITLE
How much memory is needed?

### ISSUE THREAD

**Issue by Senwang98** [filipstrand/mflux#1]
Great work, I want to try running flux on a Mac Pro, how much memory is required for the smallest model version?

**Comment by filipstrand** [comment]
Thank you! I have personally only developed and tested this on two MacBook Pro's with 32GB of ram (M1 Pro and M2 Max). Would be interesting to know if it works with only 16GB. But since you are talking about a Mac Pro I would assume this would be no problem to run (as long as it is equipped with the newer M-chips)

**Comment by Senwang98** [comment]
Okay, thanks for reply!
