### ISSUE TITLE
4bit model requires more than 9GB

### ISSUE THREAD

**Issue by sudhamjayanthi** [filipstrand/mflux#36]
haven't looked deeper into this issue yet but downloading the 4bit model requires more than 9GB for some reason. 

used the following command
```bash
mflux-save \
    --path "/Users/sdm/Desktop/code/schnell_4bit" \
    --model schnell \
    --quantize 4
```

the full precision model has been downloaded, based on the size of the .cache folder, i think:
<img width="789" alt="image" src="https://github.com/user-attachments/assets/6c50d5b8-05e2-4217-ae5f-da09d3294db4">

and then the quantised version is copied:
<img width="571" alt="image" src="https://github.com/user-attachments/assets/3e07eabd-2173-4537-81e7-e4cc0333ba8c">

so it required 43GB of free space even for the quantised version. im unsure if this a huggingface or mflux thing too. 

just flagging so people trying to download quantised version with low storage space aren't confused!

**Comment by filipstrand** [comment]
@sudhamjayanthi Good that you point this out and I should explain this more clearly in the README, but currently it works like this:

You first need to download the full non-quantised model (34 GB) and then, when you run `mflux-save`, you export a local copy of the quantized model. The quantized model is thus never downloaded from an external source. 

Once exported, you can choose to keep only the quantized model and point to it [as shown here](https://github.com/filipstrand/mflux?tab=readme-ov-file#loading-and-running-a-quantized-version-from-disk). But to reclaim the 34 GB disk space of the full model, you would have to manually delete the 34GB model from the Huggingface cache. 

Of course, it would be nice if we could host the quantized weights somewhere so that if you only wanted the 4bit version, that was the only thing you had to download.

**Comment by sudhamjayanthi** [comment]
Yeah, guessed something like that was happening! 

I'll push the quantised weights Monday if no one else does it by then, for the disk-poor.

**Comment by filipstrand** [comment]
Thanks! Please keep me posted if you do :)

**Comment by elitexp** [comment]
https://huggingface.co/madroid/flux.1-schnell-mflux-4bit and https://huggingface.co/madroid/flux.1-dev-mflux-4bit/
Seems already available, 4-bit quantized models

**Comment by filipstrand** [comment]
Oh great, did not know about this! Will add this to the README. Might have to add support for downloading these automatically too.
