### ISSUE TITLE
`seed` can't be `None`

### ISSUE THREAD

**Issue by Morriz** [filipstrand/mflux#69]
Specifying `seed` to be None as the docs say should result in a date derived seed:

```
--seed (optional, int, default: None): Seed for random number generation. Default is time-based.
```

but instead results in an error as that does not seem implemented and the function expects an `int`:

```py
    def generate_image(self, seed: int, prompt: str, config: Config = Config()) -> GeneratedImage:
        ...
        latents = mx.random.normal(
            ...
            key=mx.random.key(seed)
        )  # fmt: off
```

**Comment by anthonywu** [comment]
the `None` handling is only available when called from the CLI, implemented in `src/mflux/generate.py`

```py
    # Generate an image
    image = flux.generate_image(
        seed=int(time.time()) if args.seed is None else args.seed,  # see here
        prompt=args.prompt,
        config=Config(
            num_inference_steps=args.steps,
            height=args.height,
            width=args.width,
            guidance=args.guidance,
        ),
    )
```

I think the quickest fix for you @Morriz is to do the same in your **controller** of the image generator, when you don't have a value, pass in your preferred seed.

As for changing the mflux implementation, I think there's a valid argument for `generate_image(...)` handler to expect a not-`None` seed, because that's part of the "formula", whereas giving a default value for `seed=None` is more of a "user interface" / controller opinion.

**Comment by Morriz** [comment]
Tnx for the update. So your suggestion will end up in your code base then, yes?

**Comment by anthonywu** [comment]
@Morriz if you're on the shell calling `mflux-generate`, aren't you going through the CLI that automatically converts a `None` to a time based seed?

Otherwise, if you're calling the Python function directly, then **your code** is the controller and you have agency to pass a default non-`None` value to `generate_image(...)`. I guess I'm confused about the original request - did you somehow find the problem by using the CLI, or you copied the example code into **your workspace**, and you now have `.py` file on your computer calling `generate_image(...)` - if that's the case, you just have to pass in any `int` for `seed` arg in the `.py` code that you control.
