### ISSUE TITLE
any plans to port the ultra and raw models?

### ISSUE THREAD

**Issue by robbiemu** [filipstrand/mflux#95]
Sorry for the shabby feature request, I'm just wondering, especially since these models seem to do really good photographic appearance

**Comment by anthonywu** [comment]
This is not possible today because the weights are not publicly available. If/when posted at [huggingface.co/black-forest-labs](https://huggingface.co/black-forest-labs) then any downstream tools like `diffusers` library or this project should be able to support it with minimal change.

Big caveat - it's possible the Ultra models cannot reasonably run on consumer Mac machines, so any potential support needs to weight the cost of helping users debug/overcome hardware limitations.

**Comment by filipstrand** [comment]
I'll close this for now and make updates to the readme if anything changes regarding available models or similar
